name: test

on:
  push:
    branches:
    - main
jobs:
  my-test:
    runs-on: ubuntu-latest
    
    steps:
       - name: print HELLO message in TESTING
         run: echo "hello world from testing"
          
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my-test]
    steps:
      - name: print HELLO message in DEPLOY
        run: echo "hello wolrd from deploy"
          
          
          
          
          
        
    
    
  
  
   

