name: GITHUB-ACTION_TEST
 
on:
  push:
    branches:
    - main
    
jobs:

  my-test:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
           
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      
      
          
       
          
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my-test]
    
    
    steps:
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: routeg/gitaction:latest
          
          
      - name: show docker images
        run:  docker images
        
        
      
        
          
          
          
          
        
    
    
  
  
   

