name: test

on:
  push:
    branches:
    - main
jobs:
  my-test:
    runs-on: ubuntu-latest   
    steps:
       - name: test-testin
         run: echo "hello world from testing"
          
  my_deplot:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "hello wolrd from deploy"
          
          
          
          
          
        
    
    
  
  
   

