name: GITHUB-ACTION_TEST
env:
 APPNAME: "my flask"
 PACKEG_NAME: "flask_deploy_ver_${{github.sha}}"
 
 
on:
  push:
    branches:
    - main
    
jobs:

  my-test:
    runs-on: ubuntu-latest
    
    steps:
       - name: print HELLO message in TESTING
         run: |
          echo "hello world from testing"
          echo "TESTING ENV -- ${{ env.PACKEG_NAME }}"
          
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my-test]
    
    
    steps:
      - name: print HELLO message in DEPLOY
        run: echo "hello wolrd from deploy"
        
        
      - name: TEST ENV
        run: |
          echo "hello world test1"
          echo "hello world test2"
          echo "hello world ${{ env.APPNAME }}"
        
      - name: test dir
        run: ls -la

      - name: git clonfile
        uses: action/checkout@v1

      - name: test dir_v2
        run: ls -la
          
          
          
          
        
    
    
  
  
   

