name: GITHUB-ACTION_TEST
 
on:
  push:
    branches:
    - main
    
jobs:

  my-test:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout.
        uses: actions/checkout@v3
           
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}  
      
      - name: Build and push.
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: routeg/gitaction:${{ github.run_number }}
             
      - name: show docker images
        run:  docker images
        
        
  my-deploy:
    runs-on: test-runner 
    needs: [my-test]
    
    steps:
    
      
        
        
      - name: Stop and remove previous container
        if: always()
        run: |
           if docker ps -a --format '{{.Names}}' | grep -q container$(cat previous_build_number.txt); then
              docker stop container$(cat previous_build_number.txt)
              docker rm container$(cat previous_build_number.txt)
           fi        
      # Сохраняем текущий номер сборки в файл previous_build_number.txt
      #- name: Remove previous container
      # run: |
      #    docker ps -a | grep container | awk '{print $1 }' | xargs -I {} docker stop {} | xargs -I {} docker rm {}
      - name: run docker images 
        run: docker run -p 8082:80 --name container${{ github.run_number }}  -d routeg/gitaction:${{ github.run_number }}
        
      - name: Save previous build number 
        if: always()
        run: | 
         echo ${{ github.run_number }} > previous_build_number.txt
         
      
      
        
          
          
          
          
        
    
    
  
  
   

